name: Deploy 

on: 
  push:
    branches:
    - main
  workflow_dispatch: 


jobs:

  backend:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: |
          cd ./backend
          npm i 

      - name: Run service
        run: |
          cd ./backend
          echo "{{ secrets.BACKEND_ENV }}" > .env
          pm2 restart --update-env backend

  bot:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: |
          cd ./bot
          npm i 

      - name: Run service
        run: |
          cd ./bot
          echo "{{ secrets.BOT_ENV }}" > .env
          pm2 restart --update-env bot

  frontend:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: |
          cd ./frontend
          npm i 

      - name: Run build task
        run: |
          cd ./frontend
          npm run build 

      - name: Run service
        run: |
          cd ./frontend
          pm2 restart frontend